[package]
name = "bili-wbi-sign-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.18"
rkyv = "0.7.42"
serde = "1.0.163"
serde_derive = { version = "1.0.163", features = ["deserialize_in_place"] }
serde_json = "1.0.96"

[features]
blocking_req = ["reqwest/blocking"]
default = ["blocking_req"]
