[package]
name = "bili-wbi-sign-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
log = "0.4.18"
md5 = "0.7.0"
reqwest = "0.11.18"
rkyv = "0.7.42"
serde = "1.0.163"
serde_derive = { version = "1.0.163", features = ["deserialize_in_place"] }
serde_json = "1.0.96"
url = "2.4.0"

[features]
blocking_req = ["reqwest/blocking"]
default = ["blocking_req"]
